/**
 * Auto-feed helpers — fire-and-forget feed posts generated by system events.
 *
 * All exported functions are async but are always called with `.catch(() => {})`.
 * A failure here MUST NOT affect the caller's response.
 */

import { getSupabaseServer } from "@/lib/supabase-server";
import { createNotifications } from "@/lib/notify-inapp";
import { triggerReferralReward } from "@/lib/referrals";

type FeedPostType = "run" | "achievement" | "general";

const MILESTONE_THRESHOLDS = [1, 5, 10, 25, 50];

// ── Core insert (no throw — callers rely on this being safe) ──────────────────

async function insertPost(email: string, name: string, type: FeedPostType, body: string) {
  const db = getSupabaseServer();
  await db.from("user_posts").insert({
    author_email: email.toLowerCase(),
    author_name:  name,
    post_type:    type,
    body,
    approved:     true,
  });
}

// ── 1. Session completed ──────────────────────────────────────────────────────
// Called when attendance is marked attended=true for the first time.
// Generates a "completed session" post and, if a milestone is crossed, a
// milestone post — using user_achievements as a dedup guard.
//
// Batched to replace the N+1 pattern:
//   Before: 1 + 2N + 5M queries  (N=attendees, M=milestone hits)
//   After:  6 queries max, regardless of N

export async function autoFeedSessionCompleted(
  sessionId: string,
  attendees: { email: string; name: string }[],
): Promise<void> {
  if (!attendees.length) return;

  const db = getSupabaseServer();
  const emails = attendees.map(a => a.email.toLowerCase());
  const byEmail = Object.fromEntries(attendees.map(a => [a.email.toLowerCase(), a]));

  // ── 1 query: session title ───────────────────────────────────────────────
  const { data: session } = await db
    .from("sessions")
    .select("title")
    .eq("id", sessionId)
    .single();
  const title = session?.title ?? "a session";

  // ── 1 query: bulk "session completed" posts ──────────────────────────────
  await db.from("user_posts").insert(
    attendees.map(a => ({
      author_email: a.email.toLowerCase(),
      author_name:  a.name,
      post_type:    "run" as FeedPostType,
      body:         `🏃 ${a.name} completed ${title}`,
      approved:     true,
    })),
  );

  // ── 1 query: all attended counts in one shot (was N individual COUNTs) ───
  const { data: allAttended } = await db
    .from("session_attendance")
    .select("user_email")
    .in("user_email", emails)
    .eq("attended", true);

  const countMap: Record<string, number> = {};
  for (const row of allAttended ?? []) {
    const e = row.user_email.toLowerCase();
    countMap[e] = (countMap[e] ?? 0) + 1;
  }

  // ── First-session side effects ───────────────────────────────────────────
  const firstSessionEmails = emails.filter(e => (countMap[e] ?? 0) === 1);
  if (firstSessionEmails.length) {
    // Referral rewards: fire-and-forget, can't batch (external call per user)
    firstSessionEmails.forEach(e => triggerReferralReward(e).catch(() => {}));

    // ── 1 query: bulk upgrade-prompt notifications ───────────────────────
    createNotifications(
      firstSessionEmails.map(e => ({ email: e })),
      "upgrade_prompt",
      "You completed your first session! 🎉",
      "Get a personalised training plan from your coach and run every weekend for free.",
      "/pricing",
    ).catch(() => {});
  }

  // ── Milestone posts ──────────────────────────────────────────────────────
  const milestoneUsers = emails
    .filter(e => MILESTONE_THRESHOLDS.includes(countMap[e] ?? 0))
    .map(e => ({ email: e, name: byEmail[e]!.name, total: countMap[e] ?? 0 }));

  if (!milestoneUsers.length) return;

  // ── 1 query: upsert dedup records; ON CONFLICT DO NOTHING RETURNING *
  //    returns only rows that were just inserted — existing ones are silently
  //    skipped, so milestone posts fire exactly once per threshold crossed.
  const { data: freshAchievements } = await db
    .from("user_achievements")
    .upsert(
      milestoneUsers.map(m => ({ user_email: m.email, badge_id: `feed_milestone_${m.total}` })),
      { onConflict: "user_email,badge_id", ignoreDuplicates: true },
    )
    .select("user_email");

  if (!freshAchievements?.length) return;

  // ── 1 query: bulk milestone posts for newly crossed thresholds ───────────
  const freshSet = new Set(freshAchievements.map(r => r.user_email.toLowerCase()));
  const milestonePosts = milestoneUsers
    .filter(m => freshSet.has(m.email))
    .map(m => ({
      author_email: m.email,
      author_name:  m.name,
      post_type:    "run" as FeedPostType,
      body:         `🔥 ${m.name} reached ${m.total === 1 ? "1st session" : `${m.total} sessions`}!`,
      approved:     true,
    }));
  if (milestonePosts.length) await db.from("user_posts").insert(milestonePosts);
}

// ── 2. Badge earned ───────────────────────────────────────────────────────────
// Called once per badge when the achievement route persists a new unlock.

export async function autoFeedBadgeEarned(
  email:      string,
  badgeLabel: string,
): Promise<void> {
  const db = getSupabaseServer();

  const { data: user } = await db
    .from("users")
    .select("first_name, last_name")
    .eq("email", email.toLowerCase())
    .single();

  const name = user ? `${user.first_name} ${user.last_name}`.trim() : email.split("@")[0];

  // Strip emoji from badge label for readability: "5 Sessions 🌟" → "5 Sessions"
  const cleanLabel = badgeLabel.replace(/\s*[\u{1F300}-\u{1FAFF}\u{2600}-\u{27BF}]+\s*/gu, "").trim();

  await insertPost(
    email, name, "achievement",
    `🎖 ${name} earned the ${cleanLabel} badge`,
  );
}

// ── 3. New member joined ──────────────────────────────────────────────────────

export async function autoFeedMemberJoined(
  email:     string,
  firstName: string,
  lastName:  string,
  location?: string | null,
): Promise<void> {
  const name = `${firstName} ${lastName}`.trim();
  const loc  = location ? ` from ${location}` : "";
  await insertPost(
    email, name, "general",
    `👋 ${name} joined Connected Steps${loc} — welcome to the community! 🏃`,
  );
}

// ── 4. Membership activated ───────────────────────────────────────────────────

export async function autoFeedMembershipActivated(
  email:     string,
  name:      string,
  planLabel: string,
): Promise<void> {
  await insertPost(
    email, name, "general",
    `⭐ ${name} activated a ${planLabel} membership`,
  );
}
