/**
 * Auto-feed helpers — fire-and-forget feed posts generated by system events.
 *
 * All exported functions are async but are always called with `.catch(() => {})`.
 * A failure here MUST NOT affect the caller's response.
 */

import { getSupabaseServer } from "@/lib/supabase-server";
import { createNotification } from "@/lib/notify-inapp";
import { triggerReferralReward } from "@/lib/referrals";

type FeedPostType = "run" | "achievement" | "general";

const MILESTONE_THRESHOLDS = [1, 5, 10, 25, 50];

// ── Core insert (no throw — callers rely on this being safe) ──────────────────

async function insertPost(email: string, name: string, type: FeedPostType, body: string) {
  const db = getSupabaseServer();
  await db.from("user_posts").insert({
    author_email: email.toLowerCase(),
    author_name:  name,
    post_type:    type,
    body,
    approved:     true,
  });
}

// ── 1. Session completed ──────────────────────────────────────────────────────
// Called when attendance is marked attended=true for the first time.
// Generates a "completed session" post and, if a milestone is crossed, a
// milestone post — using user_achievements as a dedup guard.

export async function autoFeedSessionCompleted(
  sessionId: string,
  attendees: { email: string; name: string }[],
): Promise<void> {
  if (!attendees.length) return;

  const db = getSupabaseServer();

  const { data: session } = await db
    .from("sessions")
    .select("title")
    .eq("id", sessionId)
    .single();
  const title = session?.title ?? "a session";

  for (const a of attendees) {
    const email = a.email.toLowerCase();

    // Session completed post
    await insertPost(email, a.name, "run", `🏃 ${a.name} completed ${title}`);

    // Check total attended count for milestone detection
    const { count } = await db
      .from("session_attendance")
      .select("*", { count: "exact", head: true })
      .eq("user_email", email)
      .eq("attended", true);

    const total = count ?? 0;
    // First-session: trigger referral reward for the referrer (if this user was referred)
    if (total === 1) {
      triggerReferralReward(email).catch(() => {});
    }

    // First-session upgrade prompt notification (fires exactly once)
    if (total === 1) {
      createNotification({
        user_email: email,
        type:       "upgrade_prompt",
        title:      "You completed your first session! 🎉",
        body:       "Get a personalised training plan from your coach and run every weekend for free.",
        action_url: "/pricing",
      }).catch(() => {});
    }

    if (!MILESTONE_THRESHOLDS.includes(total)) continue;

    // Use user_achievements as a dedup guard with a feed-specific badge_id.
    // The unique(user_email, badge_id) constraint ensures we post exactly once.
    const { error } = await db
      .from("user_achievements")
      .insert({ user_email: email, badge_id: `feed_milestone_${total}` });

    if (!error) {
      const label = total === 1 ? "1st session" : `${total} sessions`;
      await insertPost(email, a.name, "run", `🔥 ${a.name} reached ${label}!`);
    }
  }
}

// ── 2. Badge earned ───────────────────────────────────────────────────────────
// Called once per badge when the achievement route persists a new unlock.

export async function autoFeedBadgeEarned(
  email:      string,
  badgeLabel: string,
): Promise<void> {
  const db = getSupabaseServer();

  const { data: user } = await db
    .from("users")
    .select("first_name, last_name")
    .eq("email", email.toLowerCase())
    .single();

  const name = user ? `${user.first_name} ${user.last_name}`.trim() : email.split("@")[0];

  // Strip emoji from badge label for readability: "5 Sessions 🌟" → "5 Sessions"
  const cleanLabel = badgeLabel.replace(/\s*[\u{1F300}-\u{1FAFF}\u{2600}-\u{27BF}]+\s*/gu, "").trim();

  await insertPost(
    email, name, "achievement",
    `🎖 ${name} earned the ${cleanLabel} badge`,
  );
}

// ── 3. New member joined ──────────────────────────────────────────────────────

export async function autoFeedMemberJoined(
  email:     string,
  firstName: string,
  lastName:  string,
  location?: string | null,
): Promise<void> {
  const name = `${firstName} ${lastName}`.trim();
  const loc  = location ? ` from ${location}` : "";
  await insertPost(
    email, name, "general",
    `👋 ${name} joined Connected Steps${loc} — welcome to the community! 🏃`,
  );
}

// ── 4. Membership activated ───────────────────────────────────────────────────

export async function autoFeedMembershipActivated(
  email:     string,
  name:      string,
  planLabel: string,
): Promise<void> {
  await insertPost(
    email, name, "general",
    `⭐ ${name} activated a ${planLabel} membership`,
  );
}
