/**
 * Daily Attendance QR — generation, validation, and email distribution.
 *
 * Token strategy: opaque UUID stored in daily_attendance_qr with an expires_at
 * timestamp.  The DB record IS the source of truth; scanning checks the token
 * exists and that expires_at has not passed.  No HMAC required because the token
 * is never reconstructable from public inputs (unlike event registration QRs that
 * embed the registration code).
 *
 * QR content URL: ${APP_URL}/scan?token=${uuid}&src=daily
 *   — `src=daily` tells the scan page to show the correct expired-QR message.
 */

import { getSupabaseServer } from "@/lib/supabase-server";
import { sendSingleEmail }   from "@/lib/email-service";
import type { EmailAttachment } from "@/lib/email-service";
import QRCode from "qrcode";

const APP_URL  = process.env.NEXT_PUBLIC_APP_URL ?? "https://app.connectedsteps.in";
const IST_OFFSET_MS = 5.5 * 60 * 60 * 1000;

// ── Helpers ───────────────────────────────────────────────────────────────────

function nowIST(): Date {
  return new Date(Date.now() + IST_OFFSET_MS);
}

function todayIST(): string {
  return nowIST().toISOString().slice(0, 10);
}

function fmtDateIST(iso: string): string {
  return new Date(iso).toLocaleDateString("en-IN", {
    timeZone:    "Asia/Kolkata",
    weekday:     "long",
    day:         "numeric",
    month:       "long",
    year:        "numeric",
  });
}

function fmtTimeIST(iso: string): string {
  return new Date(iso).toLocaleTimeString("en-IN", {
    timeZone: "Asia/Kolkata",
    hour:     "2-digit",
    minute:   "2-digit",
    hour12:   true,
  });
}

// ── Types ─────────────────────────────────────────────────────────────────────

export interface GeneratedQR {
  qrId:       string;
  token:      string;
  expiresAt:  string;   // ISO
  qrDataUrl:  string;   // data:image/png;base64,…
  qrBase64:   string;   // raw base64 PNG
  date:       string;   // YYYY-MM-DD
}

export interface ValidateResult {
  valid:       boolean;
  expired?:    boolean;
  qrId?:       string;
  locationId?: string | null;
  expiresAt?:  string;
}

export interface DistributeResult {
  sent:   number;
  failed: number;
}

// ── Generate ──────────────────────────────────────────────────────────────────

export async function generateDailyAttendanceQR(opts: {
  locationId?:     string | null;
  generatedBy?:    string;
  validityMinutes?: number;
  forDate?:        string;   // YYYY-MM-DD, defaults to today IST
}): Promise<GeneratedQR> {
  const db              = getSupabaseServer();
  const date            = opts.forDate ?? todayIST();
  const validityMinutes = opts.validityMinutes ?? 180;
  const generatedBy     = opts.generatedBy     ?? "system";
  const locationId      = opts.locationId       ?? null;

  const expiresAt = new Date(Date.now() + validityMinutes * 60 * 1000).toISOString();

  // Deactivate any previous QR for the same (date, location) slot
  await db
    .from("daily_attendance_qr")
    .update({ is_active: false })
    .eq("date", date)
    .is("location_id", locationId);

  // Insert new record — token is auto-generated by the DB default (gen_random_uuid())
  const { data: row, error } = await db
    .from("daily_attendance_qr")
    .insert({
      date,
      location_id:  locationId,
      expires_at:   expiresAt,
      generated_by: generatedBy,
      is_active:    true,
    })
    .select("id, token, expires_at, date")
    .single();

  if (error || !row) throw new Error(`QR insert failed: ${error?.message}`);

  const scanUrl  = `${APP_URL}/scan?token=${row.token}&src=daily`;
  const buffer   = await QRCode.toBuffer(scanUrl, { width: 400, margin: 2, errorCorrectionLevel: "H" });
  const base64   = buffer.toString("base64");
  const dataUrl  = `data:image/png;base64,${base64}`;

  return {
    qrId:      row.id,
    token:     row.token,
    expiresAt: row.expires_at,
    qrDataUrl: dataUrl,
    qrBase64:  base64,
    date:      row.date,
  };
}

// ── Validate ──────────────────────────────────────────────────────────────────

export async function validateDailyAttendanceQR(token: string): Promise<ValidateResult | null> {
  const db = getSupabaseServer();

  const { data } = await db
    .from("daily_attendance_qr")
    .select("id, expires_at, is_active, location_id")
    .eq("token", token)
    .maybeSingle();

  if (!data) return null;

  const expired = new Date(data.expires_at) < new Date();
  return {
    valid:      data.is_active && !expired,
    expired,
    qrId:       data.id,
    locationId: data.location_id,
    expiresAt:  data.expires_at,
  };
}

// ── Email template ────────────────────────────────────────────────────────────

function buildQREmailHTML(opts: {
  date:        string;
  generatedAt: string;
  expiresAt:   string;
  locationName?: string;
}): string {
  const { date, generatedAt, expiresAt, locationName } = opts;
  const displayDate = fmtDateIST(date + "T00:00:00");
  const genTime     = fmtTimeIST(generatedAt);
  const expTime     = fmtTimeIST(expiresAt);
  const loc         = locationName ? ` — ${locationName}` : "";

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <meta name="viewport" content="width=device-width,initial-scale=1"/>
  <title>Daily Attendance QR — ${displayDate}</title>
</head>
<body style="margin:0;padding:0;background:#f5f5f5;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#f5f5f5;padding:32px 16px">
    <tr><td align="center">
      <table width="600" cellpadding="0" cellspacing="0"
             style="max-width:600px;width:100%;background:#ffffff;border-radius:12px;overflow:hidden;box-shadow:0 2px 12px rgba(0,0,0,.08)">

        <!-- Header -->
        <tr>
          <td style="background:linear-gradient(135deg,#e8620a,#f07c2a);padding:28px 32px;text-align:center">
            <p style="margin:0 0 4px;font-size:13px;color:rgba(255,255,255,.8);letter-spacing:.1em;text-transform:uppercase;font-weight:600">
              Connected Steps Training${loc}
            </p>
            <h1 style="margin:0;font-size:22px;color:#fff;font-weight:800">
              Daily Attendance QR
            </h1>
            <p style="margin:8px 0 0;font-size:14px;color:rgba(255,255,255,.9);font-weight:500">
              ${displayDate}
            </p>
          </td>
        </tr>

        <!-- QR Code -->
        <tr>
          <td style="padding:32px;text-align:center">
            <p style="margin:0 0 20px;font-size:13px;color:#6b7280">
              Display this QR code at the training session for participants to scan.
            </p>
            <div style="display:inline-block;padding:16px;background:#fff;border:2px solid #e5e7eb;border-radius:12px">
              <img src="${APP_URL}/api/qr-image/${date}"
                   alt="Attendance QR Code"
                   width="280" height="280"
                   style="display:block;border-radius:4px"/>
            </div>
            <p style="margin:16px 0 0;font-size:11px;color:#9ca3af">
              If the QR image doesn't display, the QR code is also attached to this email.
            </p>
          </td>
        </tr>

        <!-- Details -->
        <tr>
          <td style="padding:0 32px 28px">
            <table width="100%" cellpadding="0" cellspacing="0"
                   style="background:#f9fafb;border:1px solid #e5e7eb;border-radius:10px;overflow:hidden">
              <tr>
                <td style="padding:14px 18px;border-bottom:1px solid #e5e7eb">
                  <span style="font-size:11px;color:#6b7280;text-transform:uppercase;font-weight:700;letter-spacing:.06em">Session Date</span>
                  <p style="margin:3px 0 0;font-size:14px;font-weight:600;color:#111">${displayDate}</p>
                </td>
              </tr>
              <tr>
                <td style="padding:14px 18px;border-bottom:1px solid #e5e7eb">
                  <span style="font-size:11px;color:#6b7280;text-transform:uppercase;font-weight:700;letter-spacing:.06em">Generated At</span>
                  <p style="margin:3px 0 0;font-size:14px;font-weight:600;color:#111">${genTime} IST</p>
                </td>
              </tr>
              <tr>
                <td style="padding:14px 18px">
                  <span style="font-size:11px;color:#6b7280;text-transform:uppercase;font-weight:700;letter-spacing:.06em">Valid Until</span>
                  <p style="margin:3px 0 0;font-size:14px;font-weight:800;color:#e8620a">${expTime} IST</p>
                </td>
              </tr>
            </table>
          </td>
        </tr>

        <!-- Instructions -->
        <tr>
          <td style="padding:0 32px 28px">
            <div style="background:#fffbf5;border:1px solid #fde68a;border-left:4px solid #e8620a;border-radius:8px;padding:16px 18px">
              <p style="margin:0 0 10px;font-size:12px;font-weight:800;color:#92400e;text-transform:uppercase;letter-spacing:.06em">
                Instructions for Trainers
              </p>
              <ul style="margin:0;padding-left:18px;font-size:13px;color:#78350f;line-height:1.7">
                <li>Open this email on your phone and display the QR code.</li>
                <li>Ask participants to open the Connected Steps app and tap <strong>Scan QR</strong>.</li>
                <li>Each participant scans the code once to mark their attendance.</li>
                <li>This QR is valid <strong>only until ${expTime} IST</strong>. Do not share after expiry.</li>
                <li>A new QR will be sent automatically tomorrow morning.</li>
              </ul>
            </div>
          </td>
        </tr>

        <!-- Footer -->
        <tr>
          <td style="background:#f9fafb;border-top:1px solid #e5e7eb;padding:20px 32px;text-align:center">
            <p style="margin:0;font-size:12px;color:#9ca3af">
              This is an automated message from Connected Steps.
              Do not reply to this email.
            </p>
          </td>
        </tr>

      </table>
    </td></tr>
  </table>
</body>
</html>`;
}

// ── Send emails to all active recipients ──────────────────────────────────────

export async function sendDailyQREmails(opts: {
  qrId:        string;
  qrBase64:    string;
  date:        string;
  generatedAt: string;
  expiresAt:   string;
  locationId?: string | null;
}): Promise<DistributeResult> {
  const { qrId, qrBase64, date, generatedAt, expiresAt, locationId } = opts;
  const db = getSupabaseServer();

  // Fetch active recipients (matching location or receiving all)
  const { data: recipients } = await db
    .from("attendance_qr_recipients")
    .select("id, name, email, location_ids")
    .eq("is_active", true);

  if (!recipients?.length) return { sent: 0, failed: 0 };

  // Filter by location
  const targets = recipients.filter(r => {
    if (!r.location_ids || r.location_ids.length === 0) return true;  // receives all
    if (!locationId) return true;                                       // global QR → all
    return r.location_ids.includes(locationId);
  });

  // Resolve location name
  let locationName: string | undefined;
  if (locationId) {
    const { data: loc } = await db
      .from("training_locations")
      .select("name")
      .eq("id", locationId)
      .maybeSingle();
    locationName = loc?.name;
  }

  const html = buildQREmailHTML({ date, generatedAt, expiresAt, locationName });
  const displayDate = fmtDateIST(date + "T00:00:00");

  // QR image is served via a public URL (/api/qr-image/[date]) embedded in the HTML.
  // Gmail and most email clients render external HTTPS images without issues.
  // The attachment is a downloadable fallback for clients that block remote images.
  const attachment: EmailAttachment = {
    content:   qrBase64,
    mime_type: "image/png",
    name:      `attendance-qr-${date}.png`,
  };

  let sent = 0;
  let failed = 0;

  for (const r of targets) {
    // Pre-insert distribution log as 'pending'
    const { data: logRow } = await db
      .from("daily_qr_distribution_log")
      .insert({
        qr_id:           qrId,
        recipient_email: r.email,
        recipient_name:  r.name,
        status:          "pending",
      })
      .select("id")
      .single();

    try {
      const result = await sendSingleEmail({
        to:          r.email,
        subject:     `Attendance QR — ${displayDate}${locationName ? ` (${locationName})` : ""}`,
        html,
        attachments: [attachment],
      });

      if (result.ok) {
        sent++;
        if (logRow) {
          await db.from("daily_qr_distribution_log")
            .update({ status: "sent" })
            .eq("id", logRow.id);
        }
      } else {
        failed++;
        if (logRow) {
          await db.from("daily_qr_distribution_log")
            .update({ status: "failed", error_message: result.error ?? "Unknown error" })
            .eq("id", logRow.id);
        }
      }
    } catch (err) {
      failed++;
      if (logRow) {
        await db.from("daily_qr_distribution_log")
          .update({ status: "failed", error_message: String(err) })
          .eq("id", logRow.id);
      }
    }
  }

  return { sent, failed };
}

// ── Fetch active settings for a location (falls back to global) ───────────────

export async function getQRSettings(locationId?: string | null) {
  const db = getSupabaseServer();

  // Try location-specific first
  if (locationId) {
    const { data: locSettings } = await db
      .from("attendance_qr_settings")
      .select("*")
      .eq("location_id", locationId)
      .maybeSingle();
    if (locSettings) return locSettings;
  }

  // Fall back to global
  const { data: global } = await db
    .from("attendance_qr_settings")
    .select("*")
    .is("location_id", null)
    .maybeSingle();

  return global ?? {
    generation_time:       "05:00",
    validity_minutes:      180,
    auto_generate_enabled: true,
    auto_email_enabled:    true,
  };
}

export { todayIST, fmtDateIST, fmtTimeIST };
