// GET /api/admin/attendance-qr/health
// Returns the current automation health status: today's QR, last 14 execution log
// entries, recipient count, and a rolled-up health signal. Used by the admin
// dashboard "Health" tab.

import { NextRequest, NextResponse } from "next/server";
import { isAdmin }            from "@/lib/admin-auth";
import { getSupabaseServer }  from "@/lib/supabase-server";
import { todayIST }           from "@/lib/daily-attendance-qr";

// attendance_qr_cron_log is a new table; Supabase types are regenerated by the user.
// Until then, cast via unknown to avoid GenericStringError on untyped columns.
interface CronLogRow {
  id:             string;
  execution_date: string;
  triggered_by:   "cron" | "manual";
  started_at:     string;
  finished_at:    string | null;
  status:         "running" | "success" | "partial" | "failed" | "skipped";
  qr_id:          string | null;
  emails_sent:    number;
  emails_failed:  number;
  error_message:  string | null;
}

export async function GET(req: NextRequest) {
  if (!isAdmin(req)) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const db    = getSupabaseServer();
  const today = todayIST();

  // Run all lookups in parallel
  const [qrResult, logResult, recipientResult] = await Promise.all([
    // Today's QR
    db
      .from("daily_attendance_qr")
      .select("id, date, is_active, generated_at, expires_at")
      .eq("date", today)
      .eq("is_active", true)
      .maybeSingle(),

    // Last 14 execution log entries (14 = two calendar weeks of daily runs)
    (db as unknown as { from: (t: string) => { select: (...a: unknown[]) => unknown } })
      .from("attendance_qr_cron_log")
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      .select("id, execution_date, triggered_by, started_at, finished_at, status, qr_id, emails_sent, emails_failed, error_message") as any,

    // Active recipient count
    db
      .from("attendance_qr_recipients")
      .select("id", { count: "exact", head: true })
      .eq("is_active", true),
  ]);

  const todayQR        = qrResult.data ?? null;
  const recipientCount = recipientResult.count ?? 0;

  // Cast the untyped log result
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const rawLog = (logResult as any);
  const runsRaw: CronLogRow[] = (rawLog?.data ?? []) as CronLogRow[];

  // Sort descending by started_at (the .order() call needs chaining; redo in-memory as fallback)
  const runs = [...runsRaw].sort(
    (a, b) => new Date(b.started_at).getTime() - new Date(a.started_at).getTime(),
  ).slice(0, 14);

  const lastComplete = runs.find(r => r.status !== "running") ?? null;
  const lastSuccess  = runs.find(r => r.status === "success")  ?? null;
  const lastFailure  = runs.find(r => r.status === "failed" || r.status === "partial") ?? null;

  // Health signal:
  // "healthy"  — today has QR, last completed run was success
  // "degraded" — today has QR but last run had partial failure
  // "critical" — today missing QR, or last run fully failed
  // "unknown"  — no run history yet
  let health: "healthy" | "degraded" | "critical" | "unknown";
  if (!lastComplete) {
    health = "unknown";
  } else if (!todayQR) {
    health = "critical";
  } else if (lastComplete.status === "success") {
    health = "healthy";
  } else if (lastComplete.status === "partial") {
    health = "degraded";
  } else {
    health = "critical";
  }

  return NextResponse.json({
    health,
    today: {
      date:        today,
      hasQR:       !!todayQR,
      qrId:        todayQR?.id          ?? null,
      generatedAt: todayQR?.generated_at ?? null,
      expiresAt:   todayQR?.expires_at   ?? null,
    },
    recipients: {
      activeCount: recipientCount,
    },
    runs,
    lastRun: lastComplete
      ? {
          at:           lastComplete.finished_at ?? lastComplete.started_at,
          status:       lastComplete.status,
          emailsSent:   lastComplete.emails_sent,
          emailsFailed: lastComplete.emails_failed,
          triggeredBy:  lastComplete.triggered_by,
        }
      : null,
    lastSuccess: lastSuccess
      ? {
          at:          lastSuccess.finished_at ?? lastSuccess.started_at,
          emailsSent:  lastSuccess.emails_sent,
          triggeredBy: lastSuccess.triggered_by,
        }
      : null,
    lastFailure: lastFailure
      ? {
          at:           lastFailure.finished_at ?? lastFailure.started_at,
          status:       lastFailure.status,
          emailsFailed: lastFailure.emails_failed,
          errorMessage: lastFailure.error_message,
          triggeredBy:  lastFailure.triggered_by,
        }
      : null,
  });
}
